routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);

Route::middleware(['auth'])->group(function () {
    Route::prefix('user')->group(function () {
        Route::get('/', [ProjectController::class, 'index']);
        Route::resource('projects', ProjectController::class);
        Route::resource('tasks', TaskController::class);
    });

    Route::get('/home', [App\Http\Controllers\ProjectController::class, 'index'])->name('home');

});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'projects';

    /**
     * The table associated with the model.
     *
     * @var array
     */
    protected $fillable = ['project_name'];

    /**
     * @return BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(User::class, 'user_projects');
    }

    /**
     * @return BelongsToMany
     */
    public function tasks()
    {
        return $this->belongsToMany(ProjectTask::class, 'project_tasks');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\ProjectService;
use App\Services\TaskService;
use App\Models\Task;
use App\Models\Project;
use App\Http\Requests\ProjectStoreRequest;
use App\Http\Requests\ProjectUpdateRequest;


class ProjectController extends Controller
{
    /**
     * @var ProjectService
     */
    private $projects;

    /**
     * @var TaskService
     */
    private $tasks;

    public function __construct(ProjectService $projects, TaskService $tasks) //сюда передается нужный объект сервиса
    {
        $this->projects = $projects; //сдесь имеем доступ к сервису
        $this->tasks = $tasks;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index() // метод для отображения данных всех проектов
    {
        return view('project.index',
            [
                "projects" => $this->projects->all(),
                "task" => $this->tasks->all(),
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()  // метод для создания
    {

        return view('project.create',
            [
                "tasks" => $this->tasks->all()
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectStoreRequest $request) // метод для сохранения нового проекта
    {
        /** @var Project $project */

        $project = $this->projects->create($request->all());
        $project->tasks()->sync($request->input('task_id'));

        return redirect()->route('projects.show', ["project" => $project->id])->withSuccess('Project #' . $project->id . 'was created!');;
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($id) // этот метод вывод конкретную модель продукта  по айдишнику из метода findById
    {
        return view('project.show',
            ["project" => $this->projects->findById($id),//метод возвращает конкретную модель по айдишнику
                "task" => $this->tasks->all()
            ]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id) // показать форму редактирования
    {

        return view('project.edit',
            [
                "project" => $this->projects->findById($id), //метод возвращает конкретную модель по айдишнику
                "task" => $this->tasks->all()
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectUpdateRequest $request, $id) // обновить отредактированый
    {
//        dd($request->all());

        /** @var Project $project */
        $project = Project::query()->find($id);

        $project->update($request->except(['_method', '_token']));
        $project->tasks()->sync($request->get('task'));

        return redirect()->route('projects.show', ["project" => $id])->withSuccess('Project #' . $id . 'was updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->projects->destroy($id);
        return redirect()->route('projects.index')->withSuccess('Project #' . $id . 'was deleted!');
    }
}

resources/views/project/create.blade.php
@extends('adminlte::page')

@section('content')
    <form method="POST" action="{{ route('projects.store') }}">

        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="project_name">Create Project</label>
                        <input type="text" class="form-control @error('project_name') is-invalid @enderror"
                               name="project_name" id="project_name"  value="{{ old('project_name') }}">
                        @error('project_name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="developers_quantity">Developers Quantity</label>
                        <input type="number" name="developers_quantity" id="developers_quantity"
                               class="form-control @error('developers_quantity') is-invalid @enderror" min="1"
                               value="{{ old('developers_quantity') }}">
                        @error('developers_quantity')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="project_technologies">Project Technologies</label>
                        <select name="technologies[]" multiple
                            class="form-control custom-select @error('technology') is-invalid @enderror">
                            <option value="Cassin-Christiansen">Cassin-Christiansen</option>
                            <option value="Olson, Gleichner and Kuhlman">Olson, Gleichner and Kuhlman</option>
                            <option value="Bode, Nienow and Metz">Bode, Nienow and Metz</option>
                            <option value="Harris, Weber and Auer">Harris, Weber and Auer</option>
                            <option value="Osinski Ltd">Osinski Ltd</option>
                            <option value="Spinka Ltd">Spinka Ltd</option>
                            <option value="Windler Ltd">Windler Ltd</option>
                            <option value="Beer, Wyman and Gaylord 1">Beer, Wyman and Gaylord 1</option>
                            <option value="555 2">555 2</option>
                        </select>
                    <input type="submit" value="Create Project" class="btn btn-info">
                    </div>
                </form>

@endsection

resources/views/project/edit.blade.php
@extends('adminlte::page')

@section('content')

    <form method="POST" action="{{ route('projects.update', ["project" => $project->id]) }}">
        @method('PUT')
        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="inputName">Project Name</label>
                        <input type="text" class="form-control @error('project_name') is-invalid @enderror"  name="project_name" id="inputName"
                               value=" {{old('project_name') ?? $project->project_name }} ">
                        @error('project_name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="developers_quantity">Developers Quantityt</label>
                        <input type="number" name="developers_quantity" id="developers_quantity" class="form-control @error('developers_quantity') is-invalid @enderror"
                               min="1" value="{{ $project->developers_quantity }}">
                        @error('developers_quantity')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror

                    </div>
                    <div class="form-group">
                        <label for="project_technologies">Project Technologies</label>
                        <select name="technology"
                                class="form-control custom-select @error('technology') is-invalid @enderror">
                            <option value="">Choose technology</option>
                            @foreach($technologies as $technology)
                                <option @if(old('technology') && $technology->technology_name === old('technology'))
                                        selected
                                        @endif
                                        value="{{ $technology->id }}">{{ $technology->technology_name }}</option>
                        @endforeach
                        </select>

                    </div>
                    <input type="submit" value="Save Changes" class="btn btn-info">
                </form>


@stop

resources/views/project/index.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials.alerts')
    <table id="projects" class="table table-bordered table-hover dataTable" role="grid"
           aria-describedby="example2_info">
        <thead>
        <tr role="row">
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Project Name
            </th>
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Project task
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Created at
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Updated at
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Actions
        </tr>
        </thead>
        <tbody>
        @foreach($projects as $project)
            <tr role="row">
                <td>{{ $project->project_name }}</td>
                <td>
                    @foreach($projects->tasks as $task)
                        {{ $task->task_name }}<br>
                    @endforeach
                </td>
                <td>{{ $project->created_at }}</td>
                <td>{{ $project->updated_at }}</td>
                <td>
                    <div class="btn-group">
                        <a href="{{ route('projects.show', ["project" => $project->id]) }}" type="button"
                           class="btn btn-info">View</a>
                        <a href="{{ route('projects.edit', ["project" => $project->id]) }}" type="button"
                           class="btn btn-info">Edit</a>
                        <form method="POST" action="{{ route('projects.destroy', ["project" => $project->id]) }}">
                            @method('DELETE')
                            @csrf
                            <input type="submit" value="delete"  class="btn btn-info">
                        </form>
                    </div>
                </td>
        @endforeach
        </tbody>
    </table>

@stop

resources/views/project/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        @include('partials.alerts')
        <div class="col-md-12">
            <div class="box-body">
                <strong><i class="fa fa-book margin-r-5"></i> {{ $project->project_name }} </strong>

                <p class="text-muted">
                    ID is # {{ $project->id }}
                </p>

                <hr>

                <strong><i class="fa fa-map-marker margin-r-5"></i> Developers quantity</strong>

                <p class="text-muted">{{ $project->developers_quantity }}</p>

                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> Project Technology</strong>

                <li> @foreach($project->technologies as $technology)
                        {{ $technology->technology_name }}</li>
                @endforeach


                <hr>


                <strong><i class="fa fa-pencil margin-r-5"></i> Time</strong>

                <p> Created at {{ $project->created_at }} </p>
                <p> Updatet at {{ $project->updated_at }} </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Description</strong>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
            </div>
            <a href="{{ route('projects.edit', ["project" => $project->id]) }}" type="button"
               class="btn btn-info">Edit</a>
        </div>




@stop